### ISSUE TITLE
Error with stopping strings

### ISSUE THREAD

**Issue by sw882882** [hallucinate-games/oobabooga-jsonformer-plugin#1]
whenever I try to use this extension, I run into this error

```
Traceback (most recent call last):
  File "/home/andrew/AI/text-generation-webui/venv/lib/python3.11/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrew/AI/text-generation-webui/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrew/AI/text-generation-webui/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrew/AI/text-generation-webui/venv/lib/python3.11/site-packages/gradio/utils.py", line 339, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrew/AI/text-generation-webui/venv/lib/python3.11/site-packages/gradio/utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrew/AI/text-generation-webui/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrew/AI/text-generation-webui/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/andrew/AI/text-generation-webui/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrew/AI/text-generation-webui/venv/lib/python3.11/site-packages/gradio/utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/andrew/AI/text-generation-webui/modules/chat.py", line 299, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, shared.history, state, regenerate, _continue, loading_message=True)):
  File "/home/andrew/AI/text-generation-webui/modules/chat.py", line 284, in generate_chat_reply
    for history in chatbot_wrapper(text, history, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "/home/andrew/AI/text-generation-webui/modules/chat.py", line 209, in chatbot_wrapper
    for j, reply in enumerate(generate_reply(prompt + cumulative_reply, state, stopping_strings=stopping_strings, is_chat=True)):
  File "/home/andrew/AI/text-generation-webui/modules/text_generation.py", line 27, in generate_reply
    for result in _generate_reply(*args, **kwargs):
  File "/home/andrew/AI/text-generation-webui/modules/text_generation.py", line 214, in _generate_reply
    for reply in generate_func(question, original_question, seed, state, stopping_strings, is_chat=is_chat):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: custom_generate_reply() missing 1 required positional argument: 'stopping_strings'
```
I tried it on a few different models and It all seemed to run into the same issue. I am using commit 847f70b6945c3af7fe5fceb9af9a00580a733c99 of the webui (should be the most recent as of writing). It also seemed to run into the issue even when I tick off the enable jsonformer plugin checkbox. 
I am using cuda 12.1 (if it matters), and 4 bit models with autogptq.

Thanks for the extension, nice to be able to use jsonformers with all the optimizations in the webui.

**Comment by blueskymonster** [comment]
Hi, will take a look later this week when I'm back home.

**Comment by blueskymonster** [comment]
@sw882882 Thanks for the heads up. Looks like a parameter was removed from `custom_generate_reply` in `text-generation-webui`. If you update the extension, it should work now.
