### ISSUE TITLE
Fails to generate anything, fails to load

### ISSUE THREAD

**Issue by Urammar** [hallucinate-games/oobabooga-jsonformer-plugin#3]
```
Traceback (most recent call last):
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\modules\chat.py", line 365, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True, for_ui=True)):
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\modules\chat.py", line 333, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message, for_ui=for_ui):
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\modules\chat.py", line 276, in chatbot_wrapper
    for j, reply in enumerate(generate_reply(prompt, state, stopping_strings=stopping_strings, is_chat=True, for_ui=for_ui)):
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 32, in generate_reply
    for result in _generate_reply(*args, **kwargs):
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 87, in _generate_reply
    for reply in generate_func(question, original_question, seed, state, stopping_strings, is_chat=is_chat):
  File "C:\MyShit\AI\oobabooga_windows\text-generation-webui\extensions\oobabooga_jsonformer_plugin\script.py", line 317, in custom_generate_reply
    elif shared.args.flexgen:
         ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'flexgen'
```

I also got an invalid char error on its default name "oobabooga-jsonformer-plugin" so I had to rename it "oobabooga_jsonformer_plugin".

**Comment by blueskymonster** [comment]
Thanks for letting me know. I haven't been playing with LLMs for several months, so this code is almost surely out of date. Next time I am on my ML machine, I will investigate this and update here.

**Comment by blueskymonster** [comment]
Hey there, this clearly got away from me. For that, I apologize.

I now no longer recommend using this extension (see explanation here: https://github.com/hallucinate-games/oobabooga-jsonformer-plugin/issues/4#issuecomment-2480375017 )
